name: Deploy Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run server in background
        run: |
          cd backend
          nohup node server.js > server.log 2>&1 &

      - name: Test server is up
        run: |
          sleep 4
          curl --fail http://localhost:3001/