
# Vercel deployment pipeline
# Brendan Dileo, June 2025

name: Vercel Deployment Workflow

on:
    push:
        branches:
            - main

jobs:
    # Only deploys if message contains [deploy]
    deploy:
        if: contains(github.event.head_commit.message, '[deploy]')
        runs-on: ubuntu-latest
        # Defines steps to run in the job
        steps:
            # Checkout from repo
            - name: Checkout Code
              uses: actions/checkout@v3
            
              # Link vercel folder to cli
            - name: Link Vercel Project
              run: npx vercel link --org ${{ secrets.VERCEL_TEAM_ID }} --project ${{ secrets.VERCEL_PRJ_ID }} --confirm

            # Deploy to vercel
            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v20
              with:
                vercel-token: ${{ secrets.VERCEL_TOKEN }}
                vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
                vercel-project-id: ${{ secrets.VERCEL_PRJ_ID }}
